import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,Check,Video} from 'lucide-react';
import {api,setCsrf} from '../api/storeApi';
import './styles.css';
function CreatorSignup(){
 const [consents,setConsents]=useState({terms:false,privacy:false,age:false});
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),all=Object.values(consents).every(Boolean);
 async function submit(event){event.preventDefault();const data=new FormData(event.currentTarget);if(data.get('password')!==data.get('confirmation')){setError('비밀번호가 일치하지 않습니다.');return}if(!all){setError('필수 항목에 모두 동의해주세요.');return}setBusy(true);setError('');try{const result=await api('/customer/creator-signup',{method:'POST',body:{username:data.get('username'),name:data.get('name'),email:data.get('email'),phone:data.get('phone'),password:data.get('password'),channel:data.get('channel'),category:data.get('category'),introduction:data.get('introduction'),consents}});setCsrf(result.csrf);location.assign(import.meta.env.BASE_URL+'creator-dashboard.html')}catch(failure){setError(failure.message);setBusy(false)}}
 return <main className="creator-signup-page"><header><a href={import.meta.env.BASE_URL+'creator-login.html'}><ArrowLeft/> 로그인으로</a><img src={`${import.meta.env.BASE_URL}logo/orange_logo.png`} alt="오렌지 라이브커머스"/></header><section className="creator-signup-intro"><span><Video/></span><div><small>ORANGE CREATOR</small><h1>크리에이터 신청</h1><p>나만의 콘텐츠와 채널 정보를 등록하고 라이브 커머스를 시작하세요.</p></div></section><ol className="creator-signup-steps"><li className="active"><b>1</b><span>계정 및 채널 정보</span></li><li><b>2</b><span>가입 완료</span></li></ol><form onSubmit={submit}>
 <fieldset><legend>기본 정보 <small>* 필수입력</small></legend><div className="creator-signup-grid"><label>이메일 *<input name="email" type="email" autoComplete="email" required maxLength="254" placeholder="example@email.com"/></label><label>아이디 *<input name="username" autoComplete="username" required pattern="[A-Za-z0-9_]{4,30}" title="영문, 숫자, 밑줄 4~30자" placeholder="영문, 숫자 4~30자"/></label><label>비밀번호 *<input name="password" type="password" autoComplete="new-password" required minLength="6" maxLength="128" placeholder="6자 이상"/></label><label>비밀번호 확인 *<input name="confirmation" type="password" autoComplete="new-password" required minLength="6" maxLength="128"/></label><label>이름 / 활동명 *<input name="name" autoComplete="name" required maxLength="60" placeholder="활동명 또는 이름"/></label><label>휴대폰 번호 *<input name="phone" type="tel" autoComplete="tel" required pattern="01[0-9]-?[0-9]{3,4}-?[0-9]{4}" placeholder="010-0000-0000"/></label></div></fieldset>
 <fieldset><legend>크리에이터 정보</legend><div className="creator-signup-grid"><label>주요 채널 URL 또는 계정 *<input name="channel" required maxLength="200" placeholder="YouTube, Instagram, TikTok 등"/></label><label>콘텐츠 분야 *<select name="category" required defaultValue=""><option value="" disabled>분야를 선택해주세요</option><option>뷰티</option><option>패션</option><option>푸드</option><option>리빙</option><option>육아</option><option>기타</option></select></label><label className="wide">소개<textarea name="introduction" maxLength="500" rows="5" placeholder="활동 내용과 강점을 간단히 소개해주세요."/></label></div></fieldset>
 <section className="creator-signup-consents"><label className="all"><input type="checkbox" checked={all} onChange={e=>setConsents({terms:e.target.checked,privacy:e.target.checked,age:e.target.checked})}/><b>내용 확인 및 전체 동의</b></label>{[['terms','서비스 이용약관 동의'],['privacy','개인정보 수집 및 이용 동의'],['age','만 14세 이상입니다.']].map(([key,text])=><label key={key}><input type="checkbox" checked={consents[key]} onChange={e=>setConsents({...consents,[key]:e.target.checked})}/>{text} <em>(필수)</em></label>)}</section>{error&&<p className="creator-signup-error" role="alert">{error}</p>}<div className="creator-signup-actions"><a href={import.meta.env.BASE_URL+'creator-login.html'}>취소</a><button disabled={busy}>{busy?'신청 중…':<><Check/> 크리에이터 신청하기</>}</button></div></form></main>}
createRoot(document.getElementById('root')).render(<CreatorSignup/>);