import React,{useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Crown,Download,RefreshCw,Search,ShoppingBag,Sparkles,UserCheck,Users,WalletCards} from 'lucide-react';
import './customer-analytics.css';

const money=value=>Number(value||0).toLocaleString('ko-KR')+'원';
const number=value=>Number(value||0).toLocaleString('ko-KR');
const csvCell=value=>'"'+String(value??'').replaceAll('"','""')+'"';
const dateValue=value=>{const date=new Date(value);return Number.isNaN(date.getTime())?null:date;};
const dateText=value=>{const date=dateValue(value);return date?date.toLocaleDateString('ko-KR'):'-';};
const segmentInfo={vip:{label:'VIP 고객',color:'#8b5ce6'},repeat:{label:'재구매 고객',color:'#2da66a'},new:{label:'신규 고객',color:'#ff641c'},general:{label:'일반 고객',color:'#3e8ce6'},inactive:{label:'휴면 고객',color:'#9aa49f'}};

export default function CustomerAnalytics({orders,loaded}){
 const tableRef=useRef(null);
 const [period,setPeriod]=useState(30),[query,setQuery]=useState(''),[segment,setSegment]=useState(''),[sort,setSort]=useState('spent'),[expanded,setExpanded]=useState('');
 const now=new Date(),cutoff=new Date(now);cutoff.setDate(cutoff.getDate()-period+1);cutoff.setHours(0,0,0,0);const inactiveCutoff=new Date(now);inactiveCutoff.setDate(inactiveCutoff.getDate()-90);
 const customers=useMemo(()=>{const map={};for(const order of orders){if(order.status==='cancelled')continue;const customer=order.customer||{};const key=String(order.userId||customer.id||customer.email||customer.phone||customer.name||'비회원');const current=map[key]||(map[key]={id:key,name:customer.name||order.customerName||'비회원 고객',email:customer.email||'',phone:customer.phone||'',orders:[],orderCount:0,totalSpent:0,periodOrders:0,periodSpent:0,firstOrder:null,lastOrder:null,products:{}});const created=dateValue(order.createdAt||order.date);current.orders.push(order);current.orderCount+=1;current.totalSpent+=Number(order.total||0);if(created&&created>=cutoff){current.periodOrders+=1;current.periodSpent+=Number(order.total||0);}if(created&&(!current.firstOrder||created<current.firstOrder))current.firstOrder=created;if(created&&(!current.lastOrder||created>current.lastOrder))current.lastOrder=created;for(const item of order.items||[]){const name=item.name||'상품명 없음';current.products[name]=(current.products[name]||0)+Number(item.quantity||1);}}return Object.values(map).map(customer=>{const favorite=Object.entries(customer.products).sort((a,b)=>b[1]-a[1])[0]?.[0]||'-';const type=customer.totalSpent>=300000||customer.orderCount>=5?'vip':customer.lastOrder&&customer.lastOrder<inactiveCutoff?'inactive':customer.orderCount>=2?'repeat':customer.firstOrder&&customer.firstOrder>=cutoff?'new':'general';return{...customer,favorite,segment:type,average:customer.orderCount?Math.round(customer.totalSpent/customer.orderCount):0};});},[orders,period]);
 const active=customers.filter(customer=>customer.periodOrders>0),newCustomers=active.filter(customer=>customer.firstOrder>=cutoff),repeatCustomers=active.filter(customer=>customer.orderCount>=2),vipCustomers=active.filter(customer=>customer.segment==='vip');
 const periodRevenue=active.reduce((sum,customer)=>sum+customer.periodSpent,0),periodOrders=active.reduce((sum,customer)=>sum+customer.periodOrders,0),average=periodOrders?Math.round(periodRevenue/periodOrders):0,repeatRate=active.length?Math.round(repeatCustomers.length/active.length*100):0;
 const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return customers.filter(customer=>(!needle||[customer.name,customer.email,customer.phone,customer.id].some(value=>String(value).toLowerCase().includes(needle)))&&(!segment||customer.segment===segment)).sort((a,b)=>sort==='orders'?b.orderCount-a.orderCount:sort==='recent'?(b.lastOrder?.getTime()||0)-(a.lastOrder?.getTime()||0):sort==='average'?b.average-a.average:b.totalSpent-a.totalSpent);},[customers,query,segment,sort]);
 const segmentData=Object.keys(segmentInfo).map(key=>({key,...segmentInfo[key],count:customers.filter(customer=>customer.segment===key).length})).filter(item=>item.count);let cursor=0;const segmentGradient=segmentData.map(item=>{const start=cursor;cursor+=customers.length?item.count/customers.length*100:0;return`${item.color} ${start}% ${cursor}%`;}).join(',');
 const topCustomers=customers.slice().sort((a,b)=>b.totalSpent-a.totalSpent).slice(0,5),maxSpent=Math.max(...topCustomers.map(customer=>customer.totalSpent),1);
 const chartDays=Math.min(period,30),activity=Array.from({length:chartDays},(_,index)=>{const date=new Date(now);date.setDate(date.getDate()-chartDays+1+index);const key=date.toLocaleDateString('en-CA');const ids=new Set();for(const order of orders){const created=dateValue(order.createdAt||order.date);if(created&&created.toLocaleDateString('en-CA')===key)ids.add(String(order.userId||order.customer?.id||order.customer?.email||order.customer?.phone||order.customer?.name||'비회원'));}return{label:`${date.getMonth()+1}.${String(date.getDate()).padStart(2,'0')}`,value:ids.size};}),maxActivity=Math.max(...activity.map(item=>item.value),1);
 const focusTable=(nextSegment='',nextSort=sort,nextQuery='')=>{setSegment(nextSegment);setSort(nextSort);setQuery(nextQuery);setTimeout(()=>tableRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);};
 const exportCsv=()=>{const output=[['고객 ID','고객명','이메일','연락처','고객 등급','총 주문수','누적 구매액','평균 주문금액','첫 주문일','최근 주문일','선호 상품'],...visible.map(customer=>[customer.id,customer.name,customer.email,customer.phone,segmentInfo[customer.segment].label,customer.orderCount,customer.totalSpent,customer.average,dateText(customer.firstOrder),dateText(customer.lastOrder),customer.favorite])];const blob=new Blob(['\ufeff'+output.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`orange-customer-analysis-${new Date().toLocaleDateString('en-CA')}.csv`;anchor.click();URL.revokeObjectURL(url);};
 if(!loaded)return <div className="customer-analysis-loading">회원 분석 데이터를 불러오는 중…</div>;
 return <section className="customer-analysis-page">
  <section className="customer-analysis-hero"><div className="customer-hero-top"><div className="customer-hero-title"><span><Users size={22}/></span><div><small>CUSTOMER INSIGHTS</small><h2>고객 관계 현황</h2><p>구매 행동을 기준으로 핵심 고객과 재구매 기회를 확인하세요.</p></div></div><div className="customer-hero-actions"><div>{[[7,'7일'],[30,'30일'],[90,'3개월'],[365,'1년']].map(([days,label])=><button key={days} className={period===days?'active':''} onClick={()=>setPeriod(days)}>{label}</button>)}</div><button onClick={exportCsv}><Download size={16}/> 고객 분석표</button></div></div><div className="customer-hero-summary"><button onClick={()=>focusTable('', 'spent')}><small>선택 기간 활성 고객</small><strong>{number(active.length)}명</strong><span>{number(periodOrders)}건 주문 · {money(periodRevenue)}</span><ArrowUpRight size={16}/></button><div><button onClick={()=>focusTable('new','recent')}><Sparkles size={18}/><span>신규 고객<b>{number(newCustomers.length)}명</b></span></button><button onClick={()=>focusTable('repeat','orders')}><RefreshCw size={18}/><span>재구매 고객<b>{number(repeatCustomers.length)}명</b></span></button><button onClick={()=>focusTable('vip','spent')}><Crown size={18}/><span>VIP 고객<b>{number(vipCustomers.length)}명</b></span></button></div></div></section>
  <div className="customer-analysis-guide"><b>분석 기준</b><span>회원 ID, 이메일, 연락처, 이름 순서로 동일 고객을 구분합니다.</span><span>취소 주문은 구매 실적에서 제외됩니다.</span><span>VIP는 누적 30만원 이상 또는 5회 이상 구매 고객입니다.</span></div>
  <div className="customer-analysis-kpis"><button onClick={()=>focusTable('', 'spent')}><span className="orange"><WalletCards size={20}/></span><div><small>고객 누적 구매액</small><strong>{money(customers.reduce((sum,customer)=>sum+customer.totalSpent,0))}</strong><p>클릭하여 구매액 순으로 보기</p></div><ArrowUpRight size={15}/></button><button onClick={()=>focusTable('repeat','orders')}><span className="green"><UserCheck size={20}/></span><div><small>재구매 고객 비율</small><strong>{repeatRate}%</strong><p>활성 고객 중 2회 이상 구매</p></div><ArrowUpRight size={15}/></button><button onClick={()=>focusTable('', 'average')}><span className="blue"><ShoppingBag size={20}/></span><div><small>평균 주문금액</small><strong>{money(average)}</strong><p>선택 기간 유효 주문 기준</p></div><ArrowUpRight size={15}/></button><button onClick={()=>focusTable('vip','spent')}><span className="purple"><Crown size={20}/></span><div><small>관리 우선 VIP</small><strong>{number(vipCustomers.length)}명</strong><p>클릭하여 VIP 고객만 보기</p></div><ArrowUpRight size={15}/></button></div>
  <div className="customer-analysis-main"><article className="customer-analysis-card customer-activity"><header><div><h3>일별 활성 고객 추이</h3><p>최근 {chartDays}일 동안 주문한 고유 고객 수입니다.</p></div><b>최대 {maxActivity}명</b></header><div className="customer-bars">{activity.map((item,index)=><div className={item.value?'has-value':'is-zero'} key={item.label} title={`${item.label} · ${item.value}명`}><span><i style={{height:`${item.value?Math.max(item.value/maxActivity*100,8):0}%`}}>{item.value>0&&<b>{item.value}</b>}</i></span>{(index===0||index===activity.length-1||item.value>0||index%5===0)&&<small>{item.label}</small>}</div>)}</div><div className="customer-chart-legend"><span><i/> 주문 고객 수</span><small>막대에 마우스를 올리면 날짜별 인원을 확인할 수 있습니다.</small></div></article><article className="customer-analysis-card customer-segments"><header><div><h3>고객 세그먼트</h3><p>누적 구매 행동 기준 분포입니다.</p></div></header><div className="customer-segment-body"><div className="customer-segment-donut" style={{background:segmentData.length?`conic-gradient(${segmentGradient})`:'#edf1ef'}}><div><strong>{number(customers.length)}</strong><small>전체 고객</small></div></div><div>{segmentData.map(item=><button key={item.key} className={segment===item.key?'active':''} onClick={()=>focusTable(item.key,item.key==='inactive'?'recent':'spent')}><span><i style={{background:item.color}}/>{item.label}</span><b>{item.count}명</b><small>{Math.round(item.count/customers.length*100)}%</small></button>)}</div></div></article></div>
  <div className="customer-analysis-lower"><article className="customer-analysis-card customer-top"><header><div><h3>우수 고객 TOP 5</h3><p>누적 구매액이 높은 고객입니다.</p></div><Crown size={18}/></header>{topCustomers.map((customer,index)=><button key={customer.id} onClick={()=>focusTable('', 'spent',customer.name)}><b>{index+1}</b><span className="customer-initial">{customer.name.slice(0,1).toUpperCase()}</span><div><strong>{customer.name}</strong><small>{customer.orderCount}회 구매 · 최근 {dateText(customer.lastOrder)}</small><i><em style={{width:`${customer.totalSpent/maxSpent*100}%`}}/></i></div><span>{money(customer.totalSpent)}</span></button>)}</article><article className="customer-analysis-card customer-opportunity"><header><div><h3>고객 관리 제안</h3><p>현재 데이터에서 바로 실행할 수 있는 작업입니다.</p></div></header><div><button onClick={()=>focusTable('inactive','recent')}><span>01</span><div><b>휴면 고객 다시 만나기</b><small>90일 이상 구매가 없는 {customers.filter(customer=>customer.segment==='inactive').length}명에게 재방문 혜택을 준비하세요.</small></div><ArrowUpRight size={16}/></button><button onClick={()=>focusTable('repeat','spent')}><span>02</span><div><b>재구매 고객 유지하기</b><small>반복 구매 고객 {repeatCustomers.length}명의 선호 상품을 확인하세요.</small></div><ArrowUpRight size={16}/></button><button onClick={()=>focusTable('new','recent')}><span>03</span><div><b>첫 구매 경험 관리하기</b><small>신규 고객 {newCustomers.length}명의 다음 구매를 위한 안내를 준비하세요.</small></div><ArrowUpRight size={16}/></button></div></article></div>
  <article ref={tableRef} className="customer-analysis-card customer-detail"><header><div><h3>고객별 구매 상세</h3><p>행을 누르면 최근 주문과 선호 상품을 확인할 수 있습니다.</p></div><span>총 {visible.length}명</span></header><div className="customer-filters"><label><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="고객명, 이메일, 연락처 검색"/></label><select value={segment} onChange={event=>setSegment(event.target.value)}><option value="">전체 고객</option>{Object.entries(segmentInfo).map(([key,item])=><option key={key} value={key}>{item.label}</option>)}</select><select value={sort} onChange={event=>setSort(event.target.value)}><option value="spent">구매액 높은순</option><option value="orders">주문 많은순</option><option value="average">평균 구매액순</option><option value="recent">최근 구매순</option></select></div><div className="customer-table-wrap"><table><thead><tr><th>고객</th><th>세그먼트</th><th>총 주문</th><th>누적 구매액</th><th>평균 구매액</th><th>최근 구매일</th><th>선호 상품</th></tr></thead><tbody>{visible.map(customer=><React.Fragment key={customer.id}><tr className="customer-row" onClick={()=>setExpanded(value=>value===customer.id?'':customer.id)}><td><div className="customer-cell"><span>{customer.name.slice(0,1).toUpperCase()}</span><div><b>{customer.name}</b><small>{customer.email||customer.phone||customer.id}</small></div></div></td><td><span className={`customer-segment ${customer.segment}`}>{segmentInfo[customer.segment].label}</span></td><td>{customer.orderCount}건</td><td><b>{money(customer.totalSpent)}</b></td><td>{money(customer.average)}</td><td>{dateText(customer.lastOrder)}</td><td>{customer.favorite}</td></tr>{expanded===customer.id&&<tr className="customer-expanded"><td colSpan="7"><div><span><small>첫 구매일</small><b>{dateText(customer.firstOrder)}</b></span><span><small>선택 기간 주문</small><b>{customer.periodOrders}건</b></span><span><small>선택 기간 구매액</small><b>{money(customer.periodSpent)}</b></span><span><small>연락처</small><b>{customer.phone||customer.email||'등록 정보 없음'}</b></span></div></td></tr>}</React.Fragment>)}</tbody></table>{!visible.length&&<div className="customer-empty"><Users size={28}/><b>조건에 맞는 고객이 없습니다.</b><span>검색어 또는 고객 세그먼트를 변경해 보세요.</span></div>}</div></article>
 </section>;
}
