import {Boxes,CheckCircle2,AlertTriangle,FileText,Grid2x2,Download,FolderOpen,Search,Trash2} from 'lucide-react';
import React,{useEffect,useMemo,useState} from 'react';
import {assetPath} from '../utils/assetPath';
import './product-list.css';

const PAGE_SIZE=10;
const statusText={published:'게시중',draft:'임시저장',hidden:'숨김'};
const csvCell=value=>'"'+String(value??'').replaceAll('"','""')+'"';

export default function ProductList({rows,loaded,busy,onCreate,onEdit,onDelete,onNavigate}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState(''),[stock,setStock]=useState(''),[brand,setBrand]=useState(''),[sort,setSort]=useState('newest'),[selected,setSelected]=useState([]),[page,setPage]=useState(0);
 const categories=useMemo(()=>[...new Set(rows.map(p=>p.category).filter(Boolean))].sort(),[rows]);
 const brands=useMemo(()=>[...new Set(rows.map(p=>p.brandName||p.origin).filter(Boolean))].sort(),[rows]);
 const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return rows.filter(p=>(!needle||[p.name,p.id,p.sku,p.category,p.brandName,p.origin].some(v=>String(v||'').toLowerCase().includes(needle)))&&(!category||p.category===category)&&(!status||p.status===status)&&(!brand||(p.brandName||p.origin)===brand)&&(!stock||(stock==='out'?Number(p.stock)===0:stock==='low'?Number(p.stock)>0&&Number(p.stock)<=10:Number(p.stock)>10))).sort((a,b)=>sort==='priceAsc'?Number(a.price)-Number(b.price):sort==='priceDesc'?Number(b.price)-Number(a.price):sort==='stockAsc'?Number(a.stock)-Number(b.stock):String(b.createdAt||b.date||b.id).localeCompare(String(a.createdAt||a.date||a.id)));},[rows,query,category,status,stock,brand,sort]);
 useEffect(()=>{setPage(0);setSelected([]);},[query,category,status,stock,brand,sort]);
 const pageRows=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE),allChecked=pageRows.length>0&&pageRows.every(p=>selected.includes(p.id));
 const reset=()=>{setQuery('');setCategory('');setStatus('');setStock('');setBrand('');setSort('newest');};
 const toggle=id=>setSelected(old=>old.includes(id)?old.filter(v=>v!==id):[...old,id]);
 const togglePage=()=>setSelected(old=>allChecked?old.filter(id=>!pageRows.some(p=>p.id===id)):[...new Set([...old,...pageRows.map(p=>p.id)])]);
 const exportCsv=()=>{const header=['ID','상품명','카테고리','브랜드','판매가','재고','상태'],body=filtered.map(p=>[p.id,p.name,p.category,p.brandName||p.origin,p.price,p.stock,statusText[p.status]||p.status]),blob=new Blob(['\ufeff'+[header,...body].map(line=>line.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`orange-products-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);};
 const stats=[[Boxes,'전체 상품',rows.length,'total'],[CheckCircle2,'게시중',rows.filter(p=>p.status==='published').length,'live'],[AlertTriangle,'품절임박',rows.filter(p=>Number(p.stock)>0&&Number(p.stock)<=10).length,'low'],[FileText,'임시저장',rows.filter(p=>p.status==='draft').length,'draft'],[Grid2x2,'카테고리 수',categories.length,'category']];
 return <section className="product-list-page">
  <div className="product-list-actions"><button onClick={()=>onNavigate('categories')}><FolderOpen size={16}/> 카테고리 관리</button><button onClick={exportCsv} disabled={!filtered.length}><Download size={16}/> 엑셀 다운로드</button><button className="admin-primary" onClick={onCreate}>+ 새 상품</button></div>
  <div className="product-filter-bar"><label className="product-search"><Search size={17}/><input aria-label="상품 검색" placeholder="상품명, 상품코드, SKU, ID를 검색하세요." value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">카테고리 전체</option>{categories.map(v=><option key={v}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">상품 상태 전체</option><option value="published">게시중</option><option value="draft">임시저장</option><option value="hidden">숨김</option></select><select value={stock} onChange={e=>setStock(e.target.value)}><option value="">재고 상태 전체</option><option value="normal">재고 충분</option><option value="low">품절임박 (10개 이하)</option><option value="out">품절</option></select><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">브랜드 전체</option>{brands.map(v=><option key={v}>{v}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">최신 등록순</option><option value="priceAsc">낮은 가격순</option><option value="priceDesc">높은 가격순</option><option value="stockAsc">재고 적은순</option></select><button onClick={reset}>초기화</button></div>
  <div className="product-stat-grid">{stats.map(([Icon,label,value,tone])=><article key={label} className={tone}><Icon size={20}/><span>{label}<strong>{value.toLocaleString()}<small>개</small></strong></span></article>)}</div>
  <div className="product-table-card"><div className="product-bulk-bar"><label><input type="checkbox" checked={allChecked} onChange={togglePage}/><b>{selected.length}개 선택됨</b></label><button className="admin-danger" disabled={!selected.length||busy} onClick={async()=>{if(!confirm(`선택한 ${selected.length}개 상품을 삭제하시겠습니까?`))return;for(const id of selected){const row=rows.find(p=>p.id===id);if(row)await onDelete(row,true);}setSelected([]);}}><Trash2 size={15}/> 선택 삭제</button><span>총 {filtered.length.toLocaleString()}개 상품</span></div><div className="admin-table-scroll"><table className="product-table"><thead><tr><th><input aria-label="현재 페이지 전체 선택" type="checkbox" checked={allChecked} onChange={togglePage}/></th><th>이미지</th><th>상품명</th><th>카테고리</th><th>브랜드</th><th>판매가</th><th>재고</th><th>상태</th><th>등록일</th><th>관리</th></tr></thead><tbody>{pageRows.map(p=><tr key={p.id}><td><input aria-label={`${p.name} 선택`} type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/></td><td>{p.image?<img className="product-thumb" src={assetPath(p.image)} alt=""/>:<span className="product-thumb empty"><Boxes size={18}/></span>}</td><td><b>{p.name}</b><small>{p.id}{p.sku?` · ${p.sku}`:''}</small></td><td><span className="product-category">{p.category||'-'}</span></td><td>{p.brandName||p.origin||'-'}</td><td><b>{Number(p.price||0).toLocaleString()}원</b></td><td className={Number(p.stock)===0?'stock-out':Number(p.stock)<=10?'stock-low':'stock-ok'}>{Number(p.stock||0).toLocaleString()}</td><td><span className={`admin-status ${p.status}`}>{statusText[p.status]||p.status||'-'}</span></td><td>{p.createdAt?new Date(p.createdAt).toLocaleDateString('ko-KR'):'-'}</td><td><div className="admin-row-actions"><button onClick={()=>onEdit(p)}>수정</button><button className="admin-danger" onClick={()=>onDelete(p)}>삭제</button></div></td></tr>)}</tbody></table>{!pageRows.length&&<p className="admin-empty">{loaded?'조건에 맞는 상품이 없습니다.':'상품을 불러오는 중…'}</p>}</div><div className="admin-pagination"><span>{filtered.length}개의 상품 중 {filtered.length?`${page*PAGE_SIZE+1}–${Math.min((page+1)*PAGE_SIZE,filtered.length)}`:'0'}개 표시</span><button disabled={!page} onClick={()=>setPage(p=>p-1)}>이전</button><b>{page+1} / {Math.max(1,Math.ceil(filtered.length/PAGE_SIZE))}</b><button disabled={(page+1)*PAGE_SIZE>=filtered.length} onClick={()=>setPage(p=>p+1)}>다음</button></div></div>
 </section>;
}
