import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,ArrowUpRight,Boxes,Download,Eye,PackageCheck,PackageSearch,Search,ShoppingBag,Warehouse} from 'lucide-react';
import {api} from '../api/storeApi';
import {assetPath} from '../utils/assetPath';
import './product-analytics.css';

const money=value=>Number(value||0).toLocaleString('ko-KR')+'원';
const number=value=>Number(value||0).toLocaleString('ko-KR');
const csvCell=value=>'"'+String(value??'').replaceAll('"','""')+'"';
const statusLabel={published:'게시중',draft:'임시저장',hidden:'숨김'};
const parseViews=value=>{const text=String(value||'0').replaceAll(',','').trim();if(text.includes('만'))return (parseFloat(text)||0)*10000;return Number(text.replace(/[^0-9.]/g,''))||0;};
const PAGE_SIZE=10;
const dateOf=value=>{const date=new Date(value);return Number.isNaN(date.getTime())?null:date;};

export default function ProductAnalytics({products,loaded}){
 const tableRef=useRef(null);
 const [orders,setOrders]=useState([]),[ordersLoaded,setOrdersLoaded]=useState(false),[period,setPeriod]=useState(30),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[stockFilter,setStockFilter]=useState(''),[sort,setSort]=useState('revenue'),[page,setPage]=useState(0);
 useEffect(()=>{let active=true;setOrdersLoaded(false);api('/admin/orders').then(data=>{if(active)setOrders(Array.isArray(data)?data:[]);}).catch(()=>{if(active)setOrders([]);}).finally(()=>{if(active)setOrdersLoaded(true);});return()=>{active=false;};},[]);
 const now=new Date(),cutoff=new Date(now);cutoff.setDate(cutoff.getDate()-period+1);cutoff.setHours(0,0,0,0);
 const scopedOrders=useMemo(()=>orders.filter(order=>{const date=dateOf(order.createdAt||order.date);return date&&date>=cutoff&&order.status!=='cancelled';}),[orders,period]);
 const sales=useMemo(()=>{const result={};for(const order of scopedOrders){for(const item of order.items||[]){const key=String(item.productId||item.id||item.name||'');if(!key)continue;const qty=Number(item.quantity||1);const lineTotal=Number(item.total||0)||Number(item.price||0)*qty;const current=result[key]||(result[key]={quantity:0,revenue:0,orders:new Set()});current.quantity+=qty;current.revenue+=lineTotal;current.orders.add(order.id);}}return result;},[scopedOrders]);
 const rows=useMemo(()=>products.map(product=>{const byId=sales[String(product.id)]||sales[String(product.productId)]||sales[String(product.name)]||{quantity:0,revenue:0,orders:new Set()};return{...product,sold:byId.quantity,revenue:byId.revenue,orderCount:byId.orders.size,viewsNumber:parseViews(product.views)};}),[products,sales]);
 const categories=useMemo(()=>[...new Set(products.map(product=>product.category).filter(Boolean))].sort(),[products]);
 const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return rows.filter(row=>(!needle||[row.name,row.id,row.category,row.origin,row.brandName].some(value=>String(value||'').toLowerCase().includes(needle)))&&(!category||row.category===category)&&(!stockFilter||(stockFilter==='ok'?Number(row.stock)>10:stockFilter==='low'?Number(row.stock)>0&&Number(row.stock)<=10:Number(row.stock)===0))).sort((a,b)=>sort==='sold'?b.sold-a.sold:sort==='stock'?Number(a.stock)-Number(b.stock):sort==='views'?b.viewsNumber-a.viewsNumber:sort==='price'?Number(b.price)-Number(a.price):b.revenue-a.revenue);},[rows,query,category,stockFilter,sort]);
 useEffect(()=>setPage(0),[query,category,stockFilter,sort,period]);
 const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));
 const pageRows=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);
 const published=products.filter(product=>product.status==='published').length;
 const lowStock=products.filter(product=>Number(product.stock)<=10).length;
 const outOfStock=products.filter(product=>Number(product.stock)===0).length;
 const inventoryValue=products.reduce((sum,product)=>sum+Number(product.price||0)*Number(product.stock||0),0);
 const totalRevenue=rows.reduce((sum,row)=>sum+row.revenue,0),totalSold=rows.reduce((sum,row)=>sum+row.sold,0);
 const topProducts=rows.slice().sort((a,b)=>b.revenue-a.revenue||b.sold-a.sold).slice(0,5),maxRevenue=Math.max(...topProducts.map(row=>row.revenue),1);
 const categoryData=categories.map((name,index)=>{const items=rows.filter(row=>row.category===name);return{name,count:items.length,revenue:items.reduce((sum,row)=>sum+row.revenue,0),color:['#ff641c','#2da66a','#3889e8','#8b62e8','#e7a225','#ea5d95'][index%6]};}).sort((a,b)=>b.count-a.count);
 let cursor=0;const categoryGradient=categoryData.map(item=>{const start=cursor;cursor+=products.length?item.count/products.length*100:0;return`${item.color} ${start}% ${cursor}%`;}).join(',');
 const focusTable=({nextSort=sort,nextCategory='',nextStock='',nextQuery=''}={})=>{setSort(nextSort);setCategory(nextCategory);setStockFilter(nextStock);setQuery(nextQuery);setTimeout(()=>tableRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);};
 const exportCsv=()=>{const output=[['상품 ID','상품명','카테고리','판매상태','판매가','재고','판매수량','주문수','매출액','조회수'],...filtered.map(row=>[row.id,row.name,row.category,statusLabel[row.status]||row.status,row.price,row.stock,row.sold,row.orderCount,row.revenue,row.viewsNumber])];const blob=new Blob(['\ufeff'+output.map(line=>line.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`orange-product-analysis-${new Date().toLocaleDateString('en-CA')}.csv`;anchor.click();URL.revokeObjectURL(url);};
 if(!loaded)return <div className="product-analysis-loading">상품 분석 데이터를 불러오는 중…</div>;
 return <section className="product-analysis-page">
  <section className="product-analysis-hero">
   <div className="product-analysis-hero-top"><div className="product-analysis-title"><span><PackageSearch size={22}/></span><div><small>PRODUCT INTELLIGENCE</small><h2>상품 성과 한눈에 보기</h2><p>판매 실적과 재고 상태를 함께 비교해 다음 운영 작업을 빠르게 결정하세요.</p></div></div><div className="product-analysis-actions"><div className="product-analysis-period">{[[7,'7일'],[30,'30일'],[90,'3개월'],[365,'1년']].map(([days,label])=><button key={days} className={period===days?'active':''} onClick={()=>setPeriod(days)}>{label}</button>)}</div><button onClick={exportCsv}><Download size={16}/> 분석표 다운로드</button></div></div>
   <div className="product-analysis-summary"><div className="product-analysis-main-number"><span>선택 기간 상품 매출</span><strong>{money(totalRevenue)}</strong><small>{totalSold?`${number(totalSold)}개 판매 · ${number(scopedOrders.length)}건 주문`:'아직 집계된 판매 내역이 없습니다.'}</small></div><div className="product-analysis-quick"><div><PackageCheck size={18}/><span>판매중 상품<b>{number(published)}개</b></span></div><div><Warehouse size={18}/><span>총 재고 자산<b>{money(inventoryValue)}</b></span></div><div className={lowStock?'warning':''}><AlertTriangle size={18}/><span>재고 확인 필요<b>{number(lowStock)}개</b></span></div></div></div>
  </section>

  <div className="product-analysis-guide"><b>운영 요약</b><span>{outOfStock?`품절 상품 ${outOfStock}개를 먼저 보충하세요.`:'현재 품절 상품이 없습니다.'}</span><span>{ordersLoaded?`최근 ${period}일 주문 데이터를 반영했습니다.`:'주문 데이터를 불러오는 중입니다.'}</span><span>재고 자산은 판매가 × 현재 재고로 계산됩니다.</span></div>

  <div className="product-analysis-kpis">
   <button type="button" onClick={()=>focusTable({nextSort:'revenue'})}><span className="orange"><Boxes size={20}/></span><div><small>전체 등록 상품</small><strong>{number(products.length)}개</strong><p>클릭하여 전체 상품 보기</p></div><ArrowUpRight className="kpi-open" size={15}/></button>
   <button type="button" onClick={()=>focusTable({nextSort:'sold'})}><span className="green"><ShoppingBag size={20}/></span><div><small>선택 기간 판매수량</small><strong>{number(totalSold)}개</strong><p>클릭하여 판매수량 순으로 보기</p></div><ArrowUpRight className="kpi-open" size={15}/></button>
   <button type="button" onClick={()=>focusTable({nextSort:'revenue'})}><span className="blue"><ArrowUpRight size={20}/></span><div><small>상품당 평균 매출</small><strong>{money(products.length?Math.round(totalRevenue/products.length):0)}</strong><p>클릭하여 매출 순으로 보기</p></div><ArrowUpRight className="kpi-open" size={15}/></button>
   <button type="button" onClick={()=>focusTable({nextSort:'views'})}><span className="purple"><Eye size={20}/></span><div><small>콘텐츠 총 조회수</small><strong>{number(rows.reduce((sum,row)=>sum+row.viewsNumber,0))}회</strong><p>클릭하여 조회수 순으로 보기</p></div><ArrowUpRight className="kpi-open" size={15}/></button>
  </div>

  <div className="product-analysis-insights">
   <article className="product-analysis-card product-ranking"><header><div><h3>매출 기여도 TOP 5</h3><p>선택 기간 매출액이 높은 상품입니다.</p></div><b>{period}일 기준</b></header><div className="product-ranking-list">{topProducts.map((row,index)=><button type="button" key={row.id} className="product-ranking-row" onClick={()=>focusTable({nextQuery:row.name,nextSort:'revenue'})} title="상품 상세표에서 보기"><b>{index+1}</b>{row.image?<img src={assetPath(row.image)} alt=""/>:<span className="ranking-image"><Boxes size={17}/></span>}<div><strong>{row.name}</strong><small>{number(row.sold)}개 판매 · {number(row.orderCount)}건 주문</small><i><em style={{width:`${row.revenue/maxRevenue*100}%`}}/></i></div><span>{money(row.revenue)}</span></button>)}</div></article>
   <article className="product-analysis-card product-category"><header><div><h3>카테고리 구성</h3><p>등록 상품 수 기준 분포입니다.</p></div></header><div className="product-category-body"><div className="product-category-donut" style={{background:categoryData.length?`conic-gradient(${categoryGradient})`:'#eef2ef'}}><div><strong>{categories.length}</strong><small>카테고리</small></div></div><div className="product-category-list">{categoryData.slice(0,6).map(item=><button type="button" key={item.name} className={category===item.name?'active':''} onClick={()=>focusTable({nextCategory:item.name})}><span><i style={{background:item.color}}/>{item.name}</span><b>{item.count}개</b><small>{products.length?Math.round(item.count/products.length*100):0}%</small></button>)}</div></div></article>
   <article className="product-analysis-card product-stock"><header><div><h3>재고 건강도</h3><p>보충이 필요한 상품을 확인하세요.</p></div></header><div className="stock-health-number"><strong>{products.length?Math.round((products.length-lowStock)/products.length*100):100}</strong><span>%<small>안정 재고 비율</small></span></div><div className="stock-health-track"><i style={{width:`${products.length?(products.length-lowStock)/products.length*100:100}%`}}/></div><dl><button type="button" className={stockFilter==='ok'?'active':''} onClick={()=>focusTable({nextSort:'stock',nextStock:'ok'})}><dt>재고 충분</dt><dd>{number(products.filter(product=>Number(product.stock)>10).length)}개</dd></button><button type="button" className={stockFilter==='low'?'active':''} onClick={()=>focusTable({nextSort:'stock',nextStock:'low'})}><dt>재고 부족</dt><dd>{number(products.filter(product=>Number(product.stock)>0&&Number(product.stock)<=10).length)}개</dd></button><button type="button" className={stockFilter==='out'?'active':''} onClick={()=>focusTable({nextSort:'stock',nextStock:'out'})}><dt>품절</dt><dd>{number(outOfStock)}개</dd></button></dl></article>
  </div>

  <article ref={tableRef} className="product-analysis-card product-performance-table"><header><div><h3>상품별 성과 상세</h3><p>검색과 정렬을 이용해 관리가 필요한 상품을 빠르게 찾을 수 있습니다.</p></div><span>총 {number(filtered.length)}개 상품</span></header><div className="product-analysis-filters"><label><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="상품명, ID, 카테고리 검색"/></label><select value={category} onChange={event=>setCategory(event.target.value)}><option value="">전체 카테고리</option>{categories.map(value=><option key={value}>{value}</option>)}</select><select value={stockFilter} onChange={event=>setStockFilter(event.target.value)}><option value="">전체 재고</option><option value="ok">재고 충분</option><option value="low">재고 부족</option><option value="out">품절</option></select><select value={sort} onChange={event=>setSort(event.target.value)}><option value="revenue">매출 높은순</option><option value="sold">판매수량 높은순</option><option value="stock">재고 적은순</option><option value="views">조회수 높은순</option><option value="price">판매가 높은순</option></select></div><div className="product-analysis-table-wrap"><table><thead><tr><th>상품</th><th>판매 상태</th><th>판매가</th><th>재고</th><th>판매수량</th><th>주문</th><th>매출액</th><th>조회수</th></tr></thead><tbody>{pageRows.map(row=><tr key={row.id}><td><div className="analysis-product-name">{row.image?<img src={assetPath(row.image)} alt=""/>:<span><Boxes size={17}/></span>}<div><b>{row.name}</b><small>#{row.id} · {row.category||'미분류'}</small></div></div></td><td><span className={`analysis-status ${row.status||'draft'}`}>{statusLabel[row.status]||'미설정'}</span></td><td><b>{money(row.price)}</b></td><td><span className={`analysis-stock ${Number(row.stock)===0?'out':Number(row.stock)<=10?'low':'ok'}`}>{number(row.stock)}개</span></td><td>{number(row.sold)}개</td><td>{number(row.orderCount)}건</td><td><strong className="analysis-revenue">{money(row.revenue)}</strong></td><td>{number(row.viewsNumber)}회</td></tr>)}</tbody></table>{!filtered.length&&<div className="product-analysis-empty"><PackageSearch size={28}/><b>조건에 맞는 상품이 없습니다.</b><span>검색어나 카테고리 필터를 변경해 보세요.</span></div>}</div><div className="admin-pagination"><span>{filtered.length}개의 상품 중 {filtered.length?`${page*PAGE_SIZE+1}–${Math.min((page+1)*PAGE_SIZE,filtered.length)}`:'0'}개 표시</span><button type="button" disabled={!page} onClick={()=>setPage(value=>value-1)}>이전</button><b>{page+1} / {pageCount}</b><button type="button" disabled={page+1>=pageCount} onClick={()=>setPage(value=>value+1)}>다음</button></div></article>
 </section>;
}
