import React, {useState} from 'react';
import {ShoppingBag, Package, Users, MessageCircle, ArrowUpRight, Gift, BarChart3, Video, Settings, Bell} from 'lucide-react';
import {assetPath} from '../utils/assetPath';
const money=n=>Number(n||0).toLocaleString('ko-KR');
const statuses={new:'신규 주문',processing:'배송 준비',shipped:'배송중',completed:'완료',cancelled:'취소'};
function Panel({title,children,onMore,className=''}){return <section className={`dash-panel ${className}`}><header><h2>{title}</h2>{onMore&&<button onClick={onMore}>전체보기 <ArrowUpRight size={13}/></button>}</header>{children}</section>}
export default function Dashboard({data,navigate}) {
 const [days,setDays]=useState(7);
 const {products=[],orders=[],reviews=[],questions=[],activity=[]}=data;
 const active=orders.filter(o=>o.status!=='cancelled');
 const today=new Date().toLocaleDateString('en-CA');
 const todayOrders=active.filter(o=>new Date(o.createdAt).toLocaleDateString('en-CA')===today);
 const deals=products.filter(p=>p.target>0&&p.status==='published'&&Date.parse(p.endsAt)>Date.now());
 const pending=questions.filter(q=>q.status==='pending').length;
 const timeline=Array.from({length:days},(_,i)=>{const d=new Date();d.setDate(d.getDate()-days+1+i);const key=d.toLocaleDateString('en-CA');return {label:`${d.getMonth()+1}/${d.getDate()}`,value:active.filter(o=>new Date(o.createdAt).toLocaleDateString('en-CA')===key).reduce((s,o)=>s+o.total,0)}});
 const max=Math.max(...timeline.map(d=>d.value),3);const points=timeline.map((d,i)=>`${48+i*492/(days-1)},${180-d.value/max*145}`).join(' ');
 const categoryTotals={};const sold={};for(const order of active)for(const item of order.items||[]){const p=products.find(p=>String(p.id)===String(item.productId));const c=p?.category||'기타';categoryTotals[c]=(categoryTotals[c]||0)+item.price*item.quantity;sold[item.productId]=(sold[item.productId]||0)+item.quantity;}
 const categories=Object.entries(categoryTotals);const total=categories.reduce((s,[,v])=>s+v,0);const colors=['#ff7929','#ffc746','#51cc95','#469cff','#a280ff','#c6ced8'];let cursor=0;const gradient=categories.map(([,v],i)=>{const start=cursor;cursor+=v/total*100;return `${colors[i%colors.length]} ${start}% ${cursor}%`}).join(',');
 const popular=products.filter(p=>sold[p.id]).sort((a,b)=>sold[b.id]-sold[a.id]).slice(0,5);
 return <div className="dash-layout"><div className="dash-center"><div className="dash-stats">{[
 [ShoppingBag,'오늘 주문 수',`${todayOrders.length}건`,'orders','접수된 주문 기준'],[Package,'판매중 상품',`${products.filter(p=>p.status==='published').length}개`,'products',`전체 상품 ${products.length}개`],[BarChart3,'오늘 주문 금액',`₩ ${money(todayOrders.reduce((s,o)=>s+o.total,0))}`,'orders','결제 매출과 별도 집계'],[Users,'진행 중인 공동구매',`${deals.length}개`,'products','현재 공개 · 종료 전 상품']
 ].map(([Icon,label,value,to,note],i)=><button className={`dash-stat tone-${i}`} key={label} onClick={()=>navigate(to)}><span className="dash-icon"><Icon size={22}/></span><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></button>)}</div>
 <div className="dash-charts"><Panel title="주문 금액 현황"><div className="dash-period">{[7,30,90].map(n=><button className={days===n?'active':''} key={n} onClick={()=>setDays(n)}>{n}일</button>)}</div><svg className="dash-chart" viewBox="0 0 570 215" role="img" aria-label={`최근 ${days}일 주문 금액 ${money(timeline.reduce((s,d)=>s+d.value,0))}원`}><defs><linearGradient id="order-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff8b42" stopOpacity=".28"/><stop offset="1" stopColor="#ff8b42" stopOpacity=".02"/></linearGradient></defs>{[0,1,2,3].map(i=><g key={i}><line x1="48" y1={35+i*145/3} x2="540" y2={35+i*145/3} stroke="#edf0f5"/><text x="42" y={39+i*145/3} textAnchor="end">{money(Math.round(max*(3-i)/3))}</text></g>)}<polygon points={`48,180 ${points} 540,180`} fill="url(#order-fill)"/><polyline points={points} fill="none" stroke="#ff761e" strokeWidth="2.5"/>{timeline.map((d,i)=>i%Math.ceil(days/7)===0||i===days-1?<g key={i}><circle cx={48+i*492/(days-1)} cy={180-d.value/max*145} r="3.5" fill="#ff761e"/><text x={48+i*492/(days-1)} y="204" textAnchor="middle">{d.label}</text></g>:null)}</svg><small className="dash-note">취소 주문 제외 · 미결제 주문 포함</small></Panel>
 <Panel title="카테고리별 주문 비율" onMore={()=>navigate('orders')}><div className="dash-category"><div className="dash-donut" style={{background:total?`conic-gradient(${gradient})`:'#edf0f5'}}><div><small>총 주문 금액</small><strong>₩ {money(total)}</strong></div></div><div className="dash-legend">{categories.length?categories.map(([name,value],i)=><p key={name}><i style={{background:colors[i%colors.length]}}/>{name}<b>{Math.round(value/total*100)}%</b></p>):<p>주문이 접수되면<br/>비율이 표시됩니다.</p>}</div></div></Panel></div>
 <div className="dash-bottom"><Panel title="최근 주문 현황" onMore={()=>navigate('orders')}><div className="admin-table-scroll"><table><thead><tr><th>상품명</th><th>고객명</th><th>상태</th><th>주문 금액</th></tr></thead><tbody>{orders.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,5).map(o=><tr key={o.id}><td>{o.items?.[0]?.name||o.id}</td><td>{o.customer?.name}</td><td><span className={`admin-status ${o.status}`}>{statuses[o.status]||o.status}</span></td><td>{money(o.total)}원</td></tr>)}</tbody></table>{!orders.length&&<div className="dash-empty"><ShoppingBag/><p>아직 접수된 주문이 없습니다.</p><small>새 주문이 들어오면 여기에 표시됩니다.</small></div>}</div></Panel>
 <Panel title="인기 상품" onMore={()=>navigate('products')}>{popular.length?<div className="dash-products">{popular.map((p,i)=><button key={p.id} onClick={()=>navigate('products')}><b>{i+1}</b><img src={assetPath(p.image)} alt=""/><span>{p.name}<small>주문 수량 {money(sold[p.id])}개</small></span><ArrowUpRight size={16}/></button>)}</div>:<div className="dash-empty"><Package/><p>주문 데이터가 아직 없습니다.</p><small>주문 수량을 기준으로 집계합니다.</small></div>}</Panel></div></div>
 <aside className="dash-right"><div className="dash-promo"><small>스토어를 더욱 특별하게</small><h2>오늘의 프로모션</h2><p>새로운 혜택을 준비해보세요!</p><button onClick={()=>navigate('promos')}>배너 관리 <ArrowUpRight size={15}/></button><Gift className="dash-gift" size={82}/></div><Panel title="최근 활동 내역" onMore={()=>navigate('audit')}><div className="dash-activity">{activity.slice(0,5).map((a,i)=><div key={a.id}><span className={`dash-icon tone-${i%4}`}><Bell size={18}/></span><p><b>{{create:'새 항목이 등록되었습니다.',update:'항목이 수정되었습니다.',delete:'항목이 삭제되었습니다.',upload:'파일이 업로드되었습니다.'}[a.action]||a.action}</b><small>{a.actor} · {a.resource}</small><time>{new Date(a.created).toLocaleString('ko-KR')}</time></p></div>)}{!activity.length&&<p className="dash-note">아직 기록된 활동이 없습니다.</p>}</div></Panel><Panel title="빠른 메뉴"><div className="dash-shortcuts">{[[Package,'상품 관리','products'],[ShoppingBag,'주문 조회','orders'],[MessageCircle,`문의 ${pending}건`,'questions'],[Video,'SNS 상품','products'],[Gift,'배너 관리','banners'],[Settings,'사이트 설정','settings']].map(([Icon,label,to])=><button key={label} onClick={()=>navigate(to)}><span><Icon size={20}/></span>{label}</button>)}</div></Panel></aside></div>;
}
