import React, {useState} from 'react';
import {ShoppingCart, Minus, Plus, CheckCircle2} from 'lucide-react';
import CheckoutForm from '../CheckoutForm/CheckoutForm';
import './styles.css';
const won=n=>n.toLocaleString('ko-KR')+'원';
export default function CartPage({cart,products,onChange,onSelect,onBack,onLike,liked}) {
 const [excluded,setExcluded]=useState([]),[checkout,setCheckout]=useState(null),[completed,setCompleted]=useState(null);
 const lines=products.filter(p=>cart[p.id]>0);
 const chosen=lines.filter(p=>!excluded.includes(String(p.id)));
 const total=chosen.reduce((sum,p)=>sum+p.price*cart[p.id],0);
 const remove=ids=>onChange(current=>Object.fromEntries(Object.entries(current).filter(([id])=>!ids.includes(String(id)))));
 const quantity=(id,value)=>{if(Number.isInteger(value)&&value>=1&&value<=99)onChange(current=>({...current,[id]:value}));};
 const start=items=>{if(!items.length)return;setCheckout(Object.fromEntries(items.map(p=>[p.id,cart[p.id]])));window.scrollTo({top:0,behavior:'instant'});};
 return <main className="cart-page wrap"><p className="cart-breadcrumb"><button onClick={onBack}>홈</button> &gt; 장바구니</p><header className="cart-heading"><h1>장바구니</h1><ol>{['장바구니','주문작성/결제','주문완료'].map((label,i)=><li key={label} aria-current={(completed?2:checkout?1:0)===i?'step':undefined}><b>{String(i+1).padStart(2,'0')}</b>{label}</li>)}</ol></header>
 {completed?<section className="cart-complete"><CheckCircle2 size={48}/><h2>주문이 접수되었습니다.</h2><p>주문번호: {completed.id}</p><strong>{won(completed.total)}</strong><p>미결제 주문입니다. 온라인 결제는 진행되지 않았습니다.</p><button className="cart-primary" onClick={onBack}>쇼핑 계속하기</button></section>:checkout?<section className="cart-checkout"><button className="cart-secondary" onClick={()=>setCheckout(null)}>장바구니로 돌아가기</button><h2>주문 상품 {Object.keys(checkout).length}개</h2><p>상품금액 {won(products.reduce((sum,p)=>sum+p.price*(checkout[p.id]||0),0))}</p><CheckoutForm cart={checkout} onComplete={result=>{setCompleted(result);onChange(current=>{const next={...current};for(const [id,count] of Object.entries(checkout)){const left=(next[id]||0)-count;if(left>0)next[id]=left;else delete next[id];}return next;});}}/></section>:<>
 <h2 className="cart-list-title">내가 담은 상품리스트</h2>
 {lines.length?<><div className="cart-table-scroll"><table className="cart-table"><thead><tr><th><input type="checkbox" aria-label="전체 상품 선택" checked={chosen.length===lines.length} onChange={e=>setExcluded(e.target.checked?[]:lines.map(p=>String(p.id)))}/></th><th>상품명/옵션</th><th>수량</th><th>상품가</th><th>주문금액</th><th>배송비</th><th>관리</th></tr></thead><tbody>{lines.map(p=><tr key={p.id}><td><input type="checkbox" aria-label={`${p.name} 선택`} checked={!excluded.includes(String(p.id))} onChange={e=>setExcluded(ids=>e.target.checked?ids.filter(id=>id!==String(p.id)):[...ids,String(p.id)])}/></td><td><button className="cart-item" onClick={()=>onSelect(p)}><img src={p.image} alt=""/><span><strong>{p.name}</strong>{p.desc&&<small>{p.desc}</small>}</span></button></td><td><div className="cart-quantity"><button aria-label={`${p.name} 수량 감소`} disabled={cart[p.id]<=1} onClick={()=>quantity(p.id,cart[p.id]-1)}><Minus size={13}/></button><input type="number" min="1" max="99" aria-label={`${p.name} 수량`} value={cart[p.id]} onChange={e=>quantity(p.id,Number(e.target.value))}/><button aria-label={`${p.name} 수량 증가`} disabled={cart[p.id]>=99} onClick={()=>quantity(p.id,cart[p.id]+1)}><Plus size={13}/></button></div></td><td>{won(p.price)}</td><td><strong>{won(p.price*cart[p.id])}</strong></td><td><b>무료배송</b><small>현재 주문 기준</small></td><td><div className="cart-row-actions"><button aria-pressed={liked.includes(p.id)} onClick={()=>onLike(p.id)}>{liked.includes(p.id)?'찜 취소':'찜하기'}</button><button onClick={()=>remove([String(p.id)])}>삭제</button></div></td></tr>)}</tbody></table></div><div className="cart-bulk"><span>선택 상품 {chosen.length}개</span><button className="cart-secondary" disabled={!chosen.length} onClick={()=>remove(chosen.map(p=>String(p.id)))}>선택삭제</button><button className="cart-secondary" onClick={()=>remove(lines.map(p=>String(p.id)))}>모두삭제</button></div>
 <section className="cart-summary" aria-label="선택 상품 합계"><div><header><b>주문금액</b><strong>{won(total)}</strong></header><dl><dt>상품금액</dt><dd>{won(total)}</dd><dt>선결제배송비</dt><dd>0원</dd></dl></div><div><header><b>할인금액</b><strong>0원</strong></header><p>추가 할인 없음</p></div><div className="cart-summary-final"><header><b>결제예정금액</b><strong>{won(total)}</strong></header><p>선택한 상품 기준</p><p>온라인 결제 없이 주문을 접수합니다.</p></div></section><div className="cart-order-actions"><button className="cart-continue" onClick={onBack}>쇼핑 계속하기</button><button className="cart-primary" onClick={()=>start(lines)}>전체주문</button><button className="cart-secondary" disabled={!chosen.length} onClick={()=>start(chosen)}>선택상품주문</button></div></>:<div className="cart-empty"><ShoppingCart size={48}/><h2>장바구니가 비어 있습니다.</h2><p>마음에 드는 상품을 담아보세요.</p><button className="cart-primary" onClick={onBack}>쇼핑 계속하기</button></div>}
 </>}
 </main>;
}
